/**
 * MUN07 IV allocation matrix — committee → country/role options.
 * Extracted from official MUN07 IV allocations. PDPA-compliant: structure only,
 * no delegate names, schools, or emails.
 */
export const MUN07_IV_ALLOCATION_COMMITTEES = [
  'UNHRC', 'UNSC', 'UNOOSA', 'DISEC', 'SPECPOL', 'ASEAN', 'Interpol', 'ICJ', 'USCC', 'PC',
] as const

export const MUN07_IV_ALLOCATIONS: Record<string, readonly string[]> = {
  UNHRC: [
    'Bolivia',
    'Brazil',
    'Canada',
    'Chile',
    'China',
    'Colombia',
    'Costa Rica',
    'Denmark',
    'El Salvador',
    'Finland',
    'France',
    'Germany',
    'Iran',
    'Iraq',
    'Mexico',
    'Netherlands',
    'Norway',
    'Russia',
    'Saudi Arabia',
    'South Africa',
    'Sweden',
    'Switzerland',
    'Syria',
    'United Kingdom',
    'United States',
    'Venezuela',
  ],
  UNSC: [
    'Australia',
    'Brazil',
    'Canada',
    'China',
    'France',
    'Germany',
    'India',
    'Indonesia',
    'Italy',
    'Japan',
    'Mongolia',
    'Netherlands',
    'North Korea',
    'Philippines',
    'Russia',
    'Singapore',
    'South Korea',
    'Spain',
    'Switzerland',
    'Taiwan',
    'Thailand',
    'United Kingdom',
    'United States',
    'Vietnam',
  ],
  UNOOSA: [
    'Argentina',
    'Australia',
    'Brazil',
    'Canada',
    'China',
    'France',
    'Germany',
    'India',
    'Iran',
    'Israel',
    'Italy',
    'Japan',
    'Kazakhstan',
    'Mexico',
    'Norway',
    'Russia',
    'Saudi Arabia',
    'South Africa',
    'South Korea',
    'Spain',
    'Sweden',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
  ],
  DISEC: [
    'Argentina',
    'Belarus',
    'Canada',
    'China',
    'Finland',
    'France',
    'Germany',
    'Iran',
    'Mexico',
    'Moldova',
    'Norway',
    'Poland',
    'Romania',
    'Russia',
    'Singapore',
    'Sweden',
    'Switzerland',
    'Thailand',
    'Ukraine',
    'United Kingdom',
    'United States',
  ],
  SPECPOL: [
    'China',
    'Egypt',
    'France',
    'Germany',
    'Iran',
    'Iraq',
    'Jordan',
    'Oman',
    'Russia',
    'Saudi Arabia',
    'Switzerland',
    'Syria',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
    'Yemen',
  ],
  ASEAN: [
    'Brunei',
    'Cambodia',
    'China',
    'East Timor',
    'Indonesia',
    'Laos',
    'Malaysia',
    'Myanmar',
    'Philippines',
    'Singapore',
    'Thailand',
    'United States',
    'Vietnam',
  ],
  Interpol: [
    'Belgium',
    'Brazil',
    'Bulgaria',
    'Cambodia',
    'Colombia',
    'France',
    'Germany',
    'Greece',
    'Hungary',
    'Iraq',
    'Italy',
    'Mexico',
    'Morocco',
    'Netherlands',
    'Nigeria',
    'Poland',
    'Portugal',
    'Romania',
    'Spain',
    'Turkey',
    'Tunisia',
    'United Kingdom',
    'United States',
    'Vietnam',
  ],
  ICJ: [
    'Mexico 1',
    'Mexico 2',
    'Mexico 3',
    'Ecuador 1',
    'Ecuador 2',
    'Ecuador 3',
    'Judge 1',
    'Judge 2',
    'Judge 3',
    'Judge 4',
    'Judge 5',
    'Judge 6',
    'Judge 7',
  ],
  USCC: [
    'D-CA Alex Padilla',
    'D-MN Amy Klobuchar',
    'D-CT Chris Murphy',
    'D-MD Chris Van Hollen',
    'D-NJ Cory Booker',
    'D-IL Dick Durbin',
    'D-MA Ed Markey',
    'D-MA Elizabeth Warren',
    'D-CO John Hickenlooper',
    'D-DE Lisa Blunt Rochester',
    'D-CT Richard Blumenthal',
    'I-VT Bernie Sanders',
    'R-AK Dan Sullivan',
    'R-OH Jon Husted',
    'R-LA John Kennedy',
    'R-FL Rick Scott',
    'R-ID Mike Crapo',
    'R-TX Ted Cruz',
    'R-AR Tom Cotton',
    'R-AL Tommy Tuberville',
    'R-SD John Thune',
    'R-WY John Barrasso',
    'R-ME Susan Collins',
    'R-UT Mike Lee',
  ],
  PC: [
    'CNN',
    'BBC News',
    'Reuters',
    'Al Jazeera',
    'The Associated Press (AP)',
    'Fox News',
    'The New York Times',
    'The Guardian',
    'Xinhua News Agency',
    'Agence France-Presse (AFP)',
    'Bloomberg',
    'Bangkok Post',
    'Euronews',
    'Russia Today',
    'Korean Central News Agency (KCNA)',
    'The Times of India',
    'Thairath',
    'Fresh News',
    'CCTV+',
    'Deutsche Welle (DW)',
  ],
}
