/**
 * Allocations for non-traditional committees, guided by THAIMUN-style conference allocations.
 * Sources: regional/country lists (Arab League, EU, IOC), role-based (UKPC, Press Corps, HCC, HSOC).
 */

/** Arab League member states (22). */
export const ARAB_LEAGUE_ALLOCATION = [
  'Algeria',
  'Bahrain',
  'Comoros',
  'Djibouti',
  'Egypt',
  'Iraq',
  'Jordan',
  'Kuwait',
  'Lebanon',
  'Libya',
  'Mauritania',
  'Morocco',
  'Oman',
  'State of Palestine',
  'Qatar',
  'Saudi Arabia',
  'Somalia',
  'Sudan',
  'Syrian Arab Republic',
  'Tunisia',
  'United Arab Emirates',
  'Yemen',
] as const

/** European Union member states (27, post-Brexit). */
export const EU_ALLOCATION = [
  'Austria',
  'Belgium',
  'Bulgaria',
  'Croatia',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Estonia',
  'Finland',
  'France',
  'Germany',
  'Greece',
  'Hungary',
  'Ireland',
  'Italy',
  'Latvia',
  'Lithuania',
  'Luxembourg',
  'Malta',
  'Netherlands',
  'Poland',
  'Portugal',
  'Romania',
  'Slovakia',
  'Slovenia',
  'Spain',
  'Sweden',
] as const

/** International Olympic Committee / IOPC: common NOC list (36 from THAIMUN-style allocation). */
export const IOC_ALLOCATION = [
  'Algeria',
  'Argentina',
  'Australia',
  'Azerbaijan',
  'Brazil',
  'Cabo Verde',
  'Cameroon',
  'Chile',
  'China',
  'Côte d\'Ivoire',
  'Cuba',
  'Djibouti',
  'Ethiopia',
  'France',
  'Guyana',
  'India',
  'Japan',
  'Kazakhstan',
  'Kenya',
  'Malaysia',
  'Mexico',
  'Morocco',
  'Netherlands',
  'New Zealand',
  'Peru',
  'Philippines',
  'Republic of Korea',
  'Russian Federation',
  'Senegal',
  'Serbia',
  'Slovenia',
  'South Africa',
  'Sweden',
  'Tunisia',
  'United Kingdom',
  'United States',
] as const

/** UK Parliament Committee (House of Commons): MP/role names with party (Labour, Conservative, Lib Dem, SNP, Reform UK). */
export const UKPC_ALLOCATION = [
  'Keir Starmer (Labour — PM)',
  'David Lammy (Labour — Justice)',
  'Rachel Reeves (Labour — Chancellor)',
  'Pat McFadden (Labour — Work & Pensions)',
  'Darren Jones (Labour — Cabinet)',
  'Yvette Cooper (Labour — Foreign Sec)',
  'John Healey (Labour — Defence)',
  'Shabana Mahmood (Labour — Home Sec)',
  'Wes Streeting (Labour — Health)',
  'Bridget Phillipson (Labour — Education)',
  'Ed Miliband (Labour — Energy)',
  'Liz Kendall (Labour — Science)',
  'Jonathan Reynolds (Labour — Whip)',
  'Heidi Alexander (Labour — Transport)',
  'Diane Abbott (Labour — MP Hackney)',
  'Bayo Alaba (Labour — MP Southend)',
  'Dawn Butler (Labour — MP Brent)',
  'Kemi Badenoch (Conservative)',
  'Mel Stride (Conservative)',
  'Priti Patel (Conservative)',
  'Chris Philp (Conservative)',
  'James Cartlidge (Conservative)',
  'Robert Jenrick (Conservative)',
  'Victoria Atkins (Conservative)',
  'Laura Trott (Conservative)',
  'Tom Tugendhat (Conservative)',
  'James Cleverly (Conservative)',
  'Ed Davey (Lib Dem)',
  'Daisy Cooper (Lib Dem)',
  'Helen Morgan (Lib Dem)',
  'Stephen Flynn (SNP)',
  'Pete Wishart (SNP)',
  'Nigel Farage (Reform UK)',
  'Richard Tice (Reform UK)',
  'Lee Anderson (Reform UK)',
] as const

/** Press Corps: media / editorial roles (outlets and roles). */
export const PRESS_CORPS_ALLOCATION = [
  'African News Agency (ANA)',
  'Agence France-Presse (AFP)',
  'Agenzia Nazionale Stampa Associata (ANSA)',
  'Al Jazeera',
  'AP News',
  'Asian News International (ANI)',
  'Australian Broadcasting Corporation (ABC)',
  'British Broadcasting Corporation (BBC)',
  'CBC (Canada)',
  'Channel News Asia (CNA)',
  'China Central Television (CCTV)',
  'DW News (Germany)',
  'Fox News (USA)',
  'Global Times (GT)',
  'Le Monde (LEM)',
  'Korean Central News Agency (KCNA)',
  'Kyodo News (Japan)',
  'NBC News (USA)',
  'New York Times (NYT)',
  'NHK (Japan)',
  'Novaya Gazeta Europe (NGE)',
  'Prensa Latina (PL)',
  'Rappler (RAP)',
  'Reuters (REU)',
  'Russia Today (RT)',
  'South China Morning Post (SCMP)',
  'The Guardian (TG)',
  'The Times of Israel (TOI)',
  'The Washington Post (WP)',
  'Xinhua News Agency (XNA)',
  'Yonhap News Agency (YNA)',
] as const

/** Historical Crisis Committee: example role names (THAIMUN-style; chairs can add custom via Other). */
export const HCC_ALLOCATION = [
  'Vladimir Putin (Pres Russia)',
  'Dmitry Medvedev (PM Russia)',
  'Sergei Shoigu (Defence Minister)',
  'Valery Gerasimov (Chief of Staff)',
  'Sergey Lavrov (Foreign Min)',
  'Oleksandr Turchynov (Acting Pres Ukraine)',
  'Arseniy Yatsenyuk (PM Ukraine)',
  'Barack Obama (US Pres)',
  'John Kerry (US Sec of State)',
  'Angela Merkel (German Chancellor)',
  'David Cameron (PM UK)',
  'Ban Ki-moon (UN SG)',
  'Xi Jinping (China Pres)',
  'Cao Cao (Wei)',
  'Sima Yi (Wei)',
  'Zhuge Liang (Shu)',
  'Lin Zexu (Viceroy)',
  'Daoguang Emperor',
  'Viscount Melbourne (British PM)',
  'Lord Palmerston (Foreign Secretary)',
  'Charles Elliot (Trade Superintendent)',
] as const

/** Historical Special Operations Committee: example role names (Korean War / Byzantine–Sassanid style). */
export const HSOC_ALLOCATION = [
  'Harry S Truman (US Pres)',
  'Dwight D. Eisenhower (US Pres)',
  'Douglas MacArthur (Commander US Forces)',
  'Matthew Ridgway (Commander US Forces)',
  'Syngman Rhee (ROK Pres)',
  'Anthony Eden (UK Foreign Sec)',
  'Kim Il Sung (DPRK Supreme Leader)',
  'Mao Zedong (PRC Chairman)',
  'Zhou Enlai (PRC PM)',
  'Joseph Stalin (Soviet Gen Sec)',
  'Ho Chi Minh (DRV Pres)',
  'Josip Broz Tito (Yugoslav Pres)',
  'Jawaharlal Nehru (PM India)',
  'Sukarno (Indonesian Pres)',
  'Shigeru Yoshida (PM Japan)',
  'Emperor Heraclius (Byzantine)',
  'Khosrow II (Sassanid)',
  'General Shahbaraz',
  'Patriarch Sergius I',
] as const
